INFO 2023-05-15 22:12:20,729 basehttp 4032 10844 "POST /auth/register/ HTTP/1.1" 201 8205
WARNING 2023-05-15 22:12:20,832 log 4032 10844 Not Found: /favicon.ico
INFO 2023-05-15 22:12:20,832 basehttp 4032 10844 - Broken pipe from ('127.0.0.1', 56140)
INFO 2023-05-15 22:12:59,419 autoreload 4032 13728 E:\uni\8\OOD\Enigma_BackEnd\Enigma\Group\serializers.py changed, reloading.
INFO 2023-05-15 22:13:00,416 autoreload 10704 16172 Watching for file changes with StatReloader
INFO 2023-05-15 22:13:00,732 views 10704 16172 new user is created!
INFO 2023-05-15 22:13:16,142 autoreload 10704 16172 E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\serializers.py changed, reloading.
INFO 2023-05-15 22:13:16,992 autoreload 16452 13228 Watching for file changes with StatReloader
INFO 2023-05-15 22:13:17,245 views 16452 13228 new user is created!
INFO 2023-05-15 22:13:31,280 autoreload 16452 13228 E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\serializers.py changed, reloading.
INFO 2023-05-15 22:13:32,334 autoreload 13664 12196 Watching for file changes with StatReloader
INFO 2023-05-15 22:13:32,650 views 13664 12196 new user is created!
WARNING 2023-05-15 22:13:36,420 log 13664 7476 Bad Request: /auth/register/
WARNING 2023-05-15 22:13:36,420 basehttp 13664 7476 "POST /auth/register/ HTTP/1.1" 400 8180
WARNING 2023-05-15 22:13:36,481 log 13664 7476 Not Found: /favicon.ico
INFO 2023-05-15 22:13:36,481 basehttp 13664 7476 - Broken pipe from ('127.0.0.1', 56454)
INFO 2023-05-15 22:13:42,610 serializers 13664 4780 new user is created!
INFO 2023-05-15 22:13:42,610 basehttp 13664 4780 "POST /auth/register/ HTTP/1.1" 201 8206
WARNING 2023-05-15 22:13:42,677 log 13664 4780 Not Found: /favicon.ico
INFO 2023-05-15 22:13:42,677 basehttp 13664 4780 - Broken pipe from ('127.0.0.1', 56496)
INFO 2023-05-15 22:20:23,255 autoreload 13664 12196 E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py changed, reloading.
INFO 2023-05-15 22:20:25,035 autoreload 14620 13168 Watching for file changes with StatReloader
INFO 2023-05-15 22:20:40,421 autoreload 14620 13168 E:\uni\8\OOD\Enigma_BackEnd\Enigma\Group\serializers.py changed, reloading.
INFO 2023-05-15 22:20:41,646 autoreload 5968 8824 Watching for file changes with StatReloader
INFO 2023-05-15 23:14:48,867 autoreload 5968 8824 E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py changed, reloading.
INFO 2023-05-15 23:14:50,913 autoreload 11072 8068 Watching for file changes with StatReloader
INFO 2023-05-15 23:16:08,339 autoreload 11072 8068 E:\uni\8\OOD\Enigma_BackEnd\Enigma\Group\views.py changed, reloading.
INFO 2023-05-15 23:16:10,077 autoreload 15228 9792 Watching for file changes with StatReloader
INFO 2023-05-15 23:18:25,570 autoreload 15228 9792 E:\uni\8\OOD\Enigma_BackEnd\Enigma\Enigma\settings.py changed, reloading.
INFO 2023-05-15 23:18:26,759 autoreload 8204 1572 Watching for file changes with StatReloader
INFO 2023-05-15 23:23:52,313 autoreload 4008 12232 Watching for file changes with StatReloader
INFO 2023-05-15 23:24:07,632 autoreload 4008 12232 E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py changed, reloading.
INFO 2023-05-15 23:24:08,498 autoreload 10040 16248 Watching for file changes with StatReloader
WARNING 2023-05-15 23:24:14,823 log 10040 14224 Not Found: /
WARNING 2023-05-15 23:24:14,823 basehttp 10040 14224 "GET / HTTP/1.1" 404 2374
WARNING 2023-05-15 23:24:14,876 log 10040 14224 Not Found: /favicon.ico
INFO 2023-05-15 23:24:14,876 basehttp 10040 14224 - Broken pipe from ('127.0.0.1', 63489)
WARNING 2023-05-15 23:24:22,003 log 10040 10252 Unauthorized: /auth/register/
WARNING 2023-05-15 23:24:22,003 basehttp 10040 10252 "GET /auth/register/ HTTP/1.1" 401 3782
INFO 2023-05-15 23:24:41,145 autoreload 10040 16248 E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py changed, reloading.
INFO 2023-05-15 23:24:42,020 autoreload 15828 13768 Watching for file changes with StatReloader
INFO 2023-05-15 23:25:01,892 autoreload 15828 13768 E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\urls.py changed, reloading.
INFO 2023-05-15 23:25:02,803 autoreload 11820 2844 Watching for file changes with StatReloader
INFO 2023-05-15 23:25:05,621 autoreload 11820 2844 E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py changed, reloading.
INFO 2023-05-15 23:25:06,598 autoreload 2292 14268 Watching for file changes with StatReloader
WARNING 2023-05-15 23:25:15,413 log 2292 11556 Unauthorized: /auth/register/
WARNING 2023-05-15 23:25:15,413 basehttp 2292 11556 "GET /auth/register/ HTTP/1.1" 401 3779
INFO 2023-05-15 23:26:03,024 autoreload 2292 14268 E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py changed, reloading.
INFO 2023-05-15 23:26:03,956 autoreload 9396 6536 Watching for file changes with StatReloader
INFO 2023-05-15 23:26:10,465 autoreload 2276 1084 Watching for file changes with StatReloader
WARNING 2023-05-15 23:26:12,735 log 2276 4344 Method Not Allowed: /auth/register/
WARNING 2023-05-15 23:26:12,735 basehttp 2276 4344 "GET /auth/register/ HTTP/1.1" 405 8044
WARNING 2023-05-15 23:26:31,174 log 2276 4344 Bad Request: /auth/register/
WARNING 2023-05-15 23:26:31,174 basehttp 2276 4344 "POST /auth/register/ HTTP/1.1" 400 8153
INFO 2023-05-15 23:26:47,373 basehttp 2276 4344 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-05-15 23:26:47,427 basehttp 2276 4344 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2215
INFO 2023-05-15 23:26:54,815 basehttp 2276 4344 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2377
INFO 2023-05-15 23:26:54,986 basehttp 2276 4344 - Broken pipe from ('127.0.0.1', 64405)
INFO 2023-05-15 23:27:04,699 basehttp 2276 14344 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2375
INFO 2023-05-15 23:27:43,049 autoreload 10876 6704 Watching for file changes with StatReloader
INFO 2023-05-15 23:27:46,242 basehttp 10876 10976 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2215
INFO 2023-05-15 23:27:56,210 basehttp 10876 10976 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2023-05-15 23:27:56,278 basehttp 10876 10976 "GET /admin/ HTTP/1.1" 200 6883
INFO 2023-05-15 23:27:56,447 basehttp 10876 10976 - Broken pipe from ('127.0.0.1', 64700)
INFO 2023-05-15 23:27:56,447 basehttp 10876 6792 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2023-05-15 23:27:56,462 basehttp 10876 14136 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2023-05-15 23:27:59,651 basehttp 10876 6792 "GET /admin/MyUser/myuser/ HTTP/1.1" 200 10687
INFO 2023-05-15 23:27:59,699 basehttp 10876 6792 - Broken pipe from ('127.0.0.1', 64709)
INFO 2023-05-15 23:27:59,715 basehttp 10876 14136 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-05-15 23:27:59,715 basehttp 10876 13700 - Broken pipe from ('127.0.0.1', 64718)
INFO 2023-05-15 23:27:59,715 basehttp 10876 1836 - Broken pipe from ('127.0.0.1', 64717)
INFO 2023-05-15 23:27:59,735 basehttp 10876 14136 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2023-05-15 23:28:18,433 basehttp 10876 14136 "GET /admin/MyUser/myuser/10/change/ HTTP/1.1" 200 11856
INFO 2023-05-15 23:28:18,470 basehttp 10876 14136 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-05-15 23:28:18,486 basehttp 10876 9180 - Broken pipe from ('127.0.0.1', 64739)
INFO 2023-05-15 23:28:18,504 basehttp 10876 14136 - Broken pipe from ('127.0.0.1', 64708)
INFO 2023-05-15 23:28:18,504 basehttp 10876 13704 - Broken pipe from ('127.0.0.1', 64740)
INFO 2023-05-15 23:28:18,520 basehttp 10876 17084 - Broken pipe from ('127.0.0.1', 64741)
INFO 2023-05-15 23:28:18,555 basehttp 10876 7408 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2023-05-15 23:28:18,555 basehttp 10876 15300 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2023-05-15 23:28:23,037 basehttp 10876 15300 "GET /admin/MyUser/myuser/10/delete/ HTTP/1.1" 200 7375
INFO 2023-05-15 23:28:23,077 basehttp 10876 15300 "GET /static/admin/js/cancel.js HTTP/1.1" 304 0
INFO 2023-05-15 23:28:24,240 basehttp 10876 15300 "POST /admin/MyUser/myuser/10/delete/ HTTP/1.1" 302 0
INFO 2023-05-15 23:28:24,256 basehttp 10876 15300 "GET /admin/MyUser/myuser/ HTTP/1.1" 200 10635
INFO 2023-05-15 23:28:24,295 basehttp 10876 15300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-05-15 23:28:24,352 basehttp 10876 15300 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2023-05-15 23:28:46,922 basehttp 10876 15300 "POST /admin/MyUser/myuser/ HTTP/1.1" 200 12225
INFO 2023-05-15 23:28:51,845 basehttp 10876 15300 "POST /admin/MyUser/myuser/ HTTP/1.1" 302 0
INFO 2023-05-15 23:28:51,860 basehttp 10876 15300 "GET /admin/MyUser/myuser/ HTTP/1.1" 200 8754
INFO 2023-05-15 23:28:51,892 basehttp 10876 15300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
ERROR 2023-05-15 23:28:59,803 log 10876 15300 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py", line 34, in post
    token, created = Token.objects.get_or_create(user=user)
                     ^^^^^
NameError: name 'Token' is not defined
ERROR 2023-05-15 23:28:59,803 basehttp 10876 15300 "POST /auth/register/ HTTP/1.1" 500 98869
INFO 2023-05-15 23:29:38,117 autoreload 10876 6704 E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py changed, reloading.
INFO 2023-05-15 23:29:39,041 autoreload 14516 4388 Watching for file changes with StatReloader
INFO 2023-05-15 23:29:48,705 basehttp 14516 5672 "GET /admin/MyUser/myuser/ HTTP/1.1" 200 8834
INFO 2023-05-15 23:29:48,737 basehttp 14516 5672 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-05-15 23:29:54,122 basehttp 14516 5672 "POST /admin/MyUser/myuser/ HTTP/1.1" 200 7537
INFO 2023-05-15 23:29:55,535 basehttp 14516 5672 "POST /admin/MyUser/myuser/ HTTP/1.1" 302 0
INFO 2023-05-15 23:29:55,551 basehttp 14516 5672 "GET /admin/MyUser/myuser/ HTTP/1.1" 200 8753
INFO 2023-05-15 23:29:55,570 basehttp 14516 5672 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
ERROR 2023-05-15 23:30:02,107 log 14516 5672 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py", line 45, in post
    email_body ='Hi '+user.username+' Use link below to verify your email \n'+absurl
                      ^^^^^^^^^^^^^
AttributeError: 'MyUser' object has no attribute 'username'
ERROR 2023-05-15 23:30:02,107 basehttp 14516 5672 "POST /auth/register/ HTTP/1.1" 500 100406
WARNING 2023-05-15 23:30:04,090 log 14516 5672 Method Not Allowed: /auth/register/
WARNING 2023-05-15 23:30:04,090 basehttp 14516 5672 "GET /auth/register/ HTTP/1.1" 405 8044
WARNING 2023-05-15 23:30:07,478 log 14516 5672 Bad Request: /auth/register/
WARNING 2023-05-15 23:30:07,478 basehttp 14516 5672 "POST /auth/register/ HTTP/1.1" 400 8153
INFO 2023-05-15 23:30:10,805 basehttp 14516 5672 "GET /admin/MyUser/myuser/ HTTP/1.1" 200 8834
INFO 2023-05-15 23:30:10,839 basehttp 14516 5672 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-05-15 23:30:17,396 basehttp 14516 5672 "POST /admin/MyUser/myuser/ HTTP/1.1" 200 7639
INFO 2023-05-15 23:30:19,018 basehttp 14516 5672 "POST /admin/MyUser/myuser/ HTTP/1.1" 302 0
INFO 2023-05-15 23:30:19,033 basehttp 14516 5672 "GET /admin/MyUser/myuser/ HTTP/1.1" 200 8753
INFO 2023-05-15 23:30:19,064 basehttp 14516 5672 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-05-15 23:30:20,368 basehttp 14516 5672 "GET /admin/MyUser/myuser/ HTTP/1.1" 200 8616
INFO 2023-05-15 23:30:20,403 basehttp 14516 3752 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
ERROR 2023-05-15 23:30:26,577 log 14516 5672 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py", line 45, in post
    email_body ='Hi '+user.username+' Use link below to verify your email \n'+absurl
                      ^^^^^^^^^^^^^
AttributeError: 'MyUser' object has no attribute 'username'
ERROR 2023-05-15 23:30:26,577 basehttp 14516 5672 "POST /auth/register/ HTTP/1.1" 500 100406
INFO 2023-05-15 23:31:13,197 autoreload 14516 4388 E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py changed, reloading.
INFO 2023-05-15 23:31:14,076 autoreload 6408 15760 Watching for file changes with StatReloader
INFO 2023-05-15 23:31:19,937 basehttp 6408 17072 "GET /admin/MyUser/myuser/ HTTP/1.1" 200 8834
INFO 2023-05-15 23:31:19,976 basehttp 6408 17072 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-05-15 23:31:25,551 basehttp 6408 17072 "POST /admin/MyUser/myuser/ HTTP/1.1" 200 7639
INFO 2023-05-15 23:31:27,030 basehttp 6408 17072 "POST /admin/MyUser/myuser/ HTTP/1.1" 302 0
INFO 2023-05-15 23:31:27,077 basehttp 6408 17072 "GET /admin/MyUser/myuser/ HTTP/1.1" 200 8753
INFO 2023-05-15 23:31:27,115 basehttp 6408 17072 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
ERROR 2023-05-15 23:31:38,367 log 6408 17072 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\views.py", line 49, in post
    Util.send_email(data)
  File "E:\uni\8\OOD\Enigma_BackEnd\Enigma\MyUser\utils.py", line 8, in send_email
    email.send()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\mail\backends\smtp.py", line 124, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\mail\backends\smtp.py", line 80, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 851, in create_connection
    raise exceptions[0]
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
ERROR 2023-05-15 23:31:38,367 basehttp 6408 17072 "POST /auth/register/ HTTP/1.1" 500 140705
INFO 2023-05-15 23:32:06,162 basehttp 6408 7784 "GET /admin/MyUser/myuser/ HTTP/1.1" 302 0
INFO 2023-05-15 23:32:29,316 autoreload 6408 15760 E:\uni\8\OOD\Enigma_BackEnd\Enigma\Group\models.py changed, reloading.
INFO 2023-05-15 23:32:32,723 autoreload 9224 13164 Watching for file changes with StatReloader
